apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production.yml -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/babblebox-default: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgresc
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgresc
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgresc
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgresc
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgresc
          image: 590183870911.dkr.ecr.us-east-1.amazonaws.com/babblebox_production_postgres
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/test
              name: production-postgres-data
            - mountPath: /backups
              name: production-postgres-data-backups
      restartPolicy: Always
      volumes:
        - name: production-postgres-data
          persistentVolumeClaim:
            claimName: production-postgres-data
        - name: production-postgres-data-backups
          persistentVolumeClaim:
            claimName: production-postgres-data-backups
